name: calculator
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans/JosefinSans-Italic.ttf
          style: italic
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans/JosefinSans-Medium.ttf
          weight: 400
